title: Jacob Charles Photography
description: Jacob Charles Photography and Videography
url: "https://rinyoon.com"
baseurl: "/jacob"
name: Jacob Charles
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
lang: "en"
