title: Jacob Charles Photography
description: Jacob Charles Photography and Videography
url: "https://rinyoon.com"
baseurl: "/jacob"
name: Jacob Charles
lang: "en"

collections:
  pages:
    output: true
    permalink: /:path/

include: ['_pages']
keep_files: [images]
plugins:
  - jekyll-email-protect
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
